---

- name: Install MariaDB packages 
  apt: name={{ item }} state=present
  # Equivalent to running "mysql_secure_installation"
  with_items: "{{mariadb_package_names}}"
  notify: secure_mariadb

- template: dest=/etc/mysql/conf.d/server.cnf owner=root mode=0664 src=server.cnf.j2
  notify: restart mariadb-debian

- copy: dest=/etc/mysql/conf.d/client.cnf owner=root mode=0664 src=client.cnf

- name: start the mariadb service
  service: name=mysql state=started enabled=yes