---

- name: Install MariaDB packages 
  yum: name={{ item }} state=present
  # Equivalent to running "mysql_secure_installation"
  with_items: "{{mariadb_package_names}}"
  notify: secure_mariadb

- template: dest=/etc/my.cnf.d/server.cnf owner=root mode=0664 src=server.cnf.j2
  notify: restart mariadb-redhat

- copy: dest=/etc/my.cnf.d/client.cnf owner=root mode=0664 src=client.cnf

- copy: dest=/etc/systemd/system/mariadb.service owner=root mode=0664 src=mariadb.service
  notify: ['restart mariadb-redhat', 'reload systemd']

- name: start the mariadb service
  service: name=mariadb state=started enabled=yes