---
# Quick Reference - https://github.com/lorin/ansible-quickref
# - hosts: all
- hosts: test
  remote_user: root
  any_errors_fatal: no
  vars:
    admin: matic

  roles:
    - {role: nginx}
   
  tasks:
    
  handlers:
  
  post_tasks:
  