---

- name: Update all existing packages on Debian
  apt: upgrade=dist cache_valid_time=3600 update_cache=yes

- name: Install common essential packages on Debian OS family
  apt: name={{ item }} state=present
  with_items:
  - "{{common_essential_packages}}"
  - "{{debian_essential_packages}}"

- name: Install common extra packages on Debian OS family
  apt: name={{ item }} state=present
  with_items:
  - "{{common_extra_packages}}"
  - "{{debian_extra_packages}}"
  when: common_install_extras == "yes"

- name: Install package unattended-upgrades for automatic updating
  apt: name=unattended-upgrades state=present
  when: common_automatic_updates == "yes"