---
# tasks file for php

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- seboolean: name={{item}} persistent=yes state=yes
  when: ansible_selinux == true
  with_items:
  - ['httpd_can_sendmail','httpd_can_network_memcache']